### ISSUE TITLE
Exception: driver not found for selenium

### ISSUE THREAD

**Issue by huseyincenik** [cullenwatson/StaffSpy#42]
Traceback (most recent call last):

  File "app.py", line 5, in <module>
    account = LinkedInAccount(
  File "anaconda3\envs\r_base_n\lib\site-packages\staffspy\__init__.py", line 33, in __init__
    self.login()
  File "anaconda3\envs\r_base_n\lib\site-packages\staffspy\__init__.py", line 38, in login
    self.session = login.load_session()
  File "anaconda3\envs\r_base_n\lib\site-packages\staffspy\utils\utils.py", line 241, in load_session
    session = self.login_browser()
  File "anaconda3\envs\r_base_n\lib\site-packages\staffspy\utils\utils.py", line 211, in login_browser
    raise Exception("driver not found for selenium")
Exception: driver not found for selenium

**Even though I installed the package as you suggested, I am still getting the "driver not found for selenium" error.**

**Comment by cullenwatson** [comment]
true, added a way to specify the path of your installed chromedriver

```py
account = LinkedInAccount(
     driver_type=DriverType(
         browser_type=BrowserType.CHROME,
         executable_path="/Users/pc/chromedriver-mac-arm64/chromedriver"
    ),
)
```

**Comment by huseyincenik** [comment]
Thank you
